#ifndef CONFIG_H
#define CONFIG_H

#define GUAVAOS_TOTAL_INTERRUPTS 512
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

// 100MB heap size
#define GUAVAOS_HEAP_SIZE_BYTES 104857600
#define GUAVAOS_HEAP_BLOCK_SIZE 4096
#define GUAVAOS_HEAP_ADDRESS 0x01000000


#define GUAVAOS_HEAP_TABLE_ADDRESS 0x00007E00

#define GUAVAOS_SECTOR_SIZE 512


#define GUAVAOS_MAX_FILESYSTEMS 12
#define GUAVAOS_MAX_FILE_DESCRIPTORS 512

#define GUAVAOS_TOTAL_GDT_SEGMENTS 6

#define GUAVAOS_PROGRAM_VIRTUAL_ADDRESS 0x400000

#define GUAVAOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b
#define GUAVAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3ff000
#define GUAVAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END GUAVAOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - GUAVAOS_USER_PROGRAM_STACK_SIZE

#define GUAVAOS_MAX_PROGRAM_ALLOCATIONS 1024
#define GUAVAOS_MAX_PROCESSES 12

#endif